plugins {
    id 'com.android.library'
    id 'kotlin-android'
}

group 'org.sigrok.flutter_libserialport'
version '0.5.0-SNAPSHOT'

allprojects {
    repositories {
        google()
        mavenCentral()  // Replacing jcenter() since it's deprecated
    }
}

android {
    namespace "org.sigrok.flutter_libserialport"
    compileSdkVersion 34

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    defaultConfig {
        minSdkVersion 21
    }

    lintOptions {
        disable 'InvalidPackage'
    }

    externalNativeBuild {
        cmake {
            path "libserialport/CMakeLists.txt"
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = '17'
    }

    buildToolsVersion '34.0.0'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib:1.9.10"
}
